import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:workmanager/workmanager.dart';
import 'package:window_manager/window_manager.dart';
import 'core/constants.dart';
import 'data/models/contributor.dart';
import 'data/models/contributor_detail.dart';
import 'data/models/movie_detail.dart';
import 'data/models/movie_cache_entry.dart';
import 'data/models/tv_cache.dart';
import 'data/models/notification_history.dart';
import 'data/models/preferences.dart';
import 'data/models/tv_detail.dart';
import 'ui/screens/main_screen.dart';
import 'ui/common/rate_limit_listener.dart';
import 'logic/background_service.dart';
import 'package:flutter_phoenix/flutter_phoenix.dart';
import 'providers/providers.dart';

import 'package:path_provider/path_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Configure image cache to prevent unbounded memory growth
  imageCache.maximumSize = 100; // Maximum number of images to cache
  imageCache.maximumSizeBytes = 50 * 1024 * 1024; // 50MB maximum cache size

  // 0. Initialize window manager (Windows only)
  if (Platform.isWindows) {
    debugPrint('[Main] Initializing window manager for Windows');
    await windowManager.ensureInitialized();
    debugPrint('[Main] Window manager initialized');
    
    WindowOptions windowOptions = const WindowOptions(
      size: Size(1280, 720),
      center: true,
      backgroundColor: Colors.transparent,
      skipTaskbar: false,
      titleBarStyle: TitleBarStyle.normal,
    );
    
    debugPrint('[Main] Setting up window ready callback');
    windowManager.waitUntilReadyToShow(windowOptions, () async {
      debugPrint('[Main] Window ready callback - showing and focusing window');
      await windowManager.show();
      await windowManager.focus();
      
      // Set prevent close to true from the start
      debugPrint('[Main] Setting preventClose to true');
      await windowManager.setPreventClose(true);
      debugPrint('[Main] Window shown, focused, and preventClose set');
    });
  } else {
    debugPrint('[Main] Skipping window manager - not Windows platform');
  }

  // 1. Load Environment Variables
  await dotenv.load(fileName: ".env");

  // 2. Initialize Hive
  if (Platform.isWindows) {
    final appSupportDir = await getApplicationSupportDirectory();
    await Hive.initFlutter(appSupportDir.path);
  } else {
    await Hive.initFlutter();
  }

  // 3. Register Adapters (Generated by build_runner)
  Hive.registerAdapter(ContributorAdapter());
  Hive.registerAdapter(ContributorTypeAdapter());
  Hive.registerAdapter(TvNotificationPreferencesAdapter());
  Hive.registerAdapter(LatestWorkAdapter());
  Hive.registerAdapter(PreferencesAdapter());
  Hive.registerAdapter(NotificationHistoryEntryAdapter());
  Hive.registerAdapter(NotificationReasonAdapter());
  Hive.registerAdapter(NotificationEventAdapter());
  Hive.registerAdapter(MovieCacheEntryAdapter());
  Hive.registerAdapter(TvShowCacheEntryAdapter());
  Hive.registerAdapter(TvEpisodeCacheEntryAdapter());
  
  // Register new contributor details adapters
  Hive.registerAdapter(WorkTypeAdapter());
  Hive.registerAdapter(ReleaseTypeAdapter());
  Hive.registerAdapter(StreamingTypeAdapter());
  Hive.registerAdapter(ContributorRoleAdapter());
  Hive.registerAdapter(StreamingOptionAdapter());
  Hive.registerAdapter(WorkAdapter());
  Hive.registerAdapter(ContributorDetailAdapter());
  Hive.registerAdapter(CastMemberAdapter());
  Hive.registerAdapter(CrewMemberAdapter());
  Hive.registerAdapter(MovieDetailAdapter());
  Hive.registerAdapter(TvShowDetailAdapter());
  Hive.registerAdapter(TvSeasonAdapter());
  Hive.registerAdapter(TvEpisodeDetailAdapter());
  Hive.registerAdapter(TvSeasonDetailAdapter());
  Hive.registerAdapter(SeasonEpisodeAdapter());

  // 4. Open Boxes
  await Hive.openBox<Contributor>(AppConstants.contributorsBox);
  await Hive.openBox<Preferences>(AppConstants.preferencesBox);
  await Hive.openBox<NotificationHistoryEntry>(AppConstants.historyBox);
  await Hive.openBox<MovieCacheEntry>(AppConstants.movieCacheBox);
  
  // Open new boxes for contributor details
  await Hive.openBox<ContributorDetail>(AppConstants.contributorDetailsBox);
  await Hive.openBox<MovieDetail>(AppConstants.movieDetailsBox);
  await Hive.openBox<TvShowDetail>(AppConstants.tvDetailsBox);
  await Hive.openBox<TvEpisodeDetail>(AppConstants.tvEpisodeDetailsBox);
  await Hive.openBox<TvSeasonDetail>(AppConstants.tvSeasonDetailsBox);

  // 5. Initialize Riverpod Container
  final container = ProviderContainer();

  // 6. Initialize TV Cache Repository
  final tvCacheRepo = container.read(tvCacheRepositoryProvider);
  await tvCacheRepo.init();

  // 7. Initialize Notification Service with callback for navigation
  final notificationService = container.read(notificationServiceProvider);
  await notificationService.init(
    onAction: (payload) {
      if (payload == 'app://history') {
        // Navigate to history tab
        container.read(selectedTabProvider.notifier).state = 1; // History tab index
      }
    },
  );

  // 8. Initialize System Tray (Windows only)
  if (Platform.isWindows) {
    debugPrint('[Main] Initializing system tray service for Windows');
    final systemTrayService = container.read(systemTrayServiceProvider);
    systemTrayService.setContainer(container); // Pass the container for release checking
    await systemTrayService.init();
    debugPrint('[Main] System tray service initialization completed');
  } else {
    debugPrint('[Main] Skipping system tray - not Windows platform');
  }

  // 9. Initialize Workmanager (Mobile only)
  if (!kIsWeb && (Platform.isAndroid || Platform.isIOS)) {
    await Workmanager().initialize(
      callbackDispatcher,
      isInDebugMode: kDebugMode,
    );
    
    // Calculate initial delay for 9:00 AM
    final now = DateTime.now();
    var firstRun = DateTime(now.year, now.month, now.day, 9, 0);
    if (firstRun.isBefore(now)) {
      firstRun = firstRun.add(const Duration(days: 1));
    }
    final initialDelay = firstRun.difference(now);

    await Workmanager().registerPeriodicTask(
      "daily-check-task",
      taskName,
      frequency: const Duration(hours: 24),
      initialDelay: initialDelay,
      constraints: Constraints(
        networkType: NetworkType.connected,
      ),
    );
  } else {
    debugPrint('[Main] Workmanager not supported on this platform. Background tasks skipped.');
  }

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: Phoenix(
        child: const MyApp(),
      ),
    ),
  );
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final prefsAsync = ref.watch(preferencesProvider);
    
    return prefsAsync.when(
      data: (prefs) {
        final useDarkMode = prefs.useDarkMode ?? false;
        
        return MaterialApp(
          title: 'Filmmaker Alerts',
          theme: ThemeData(
            colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
            useMaterial3: true,
            snackBarTheme: const SnackBarThemeData(
              behavior: SnackBarBehavior.floating,
            ),
          ),
          darkTheme: ThemeData(
            colorScheme: ColorScheme.fromSeed(
              seedColor: Colors.deepPurple,
              brightness: Brightness.dark,
            ),
            useMaterial3: true,
            snackBarTheme: const SnackBarThemeData(
              behavior: SnackBarBehavior.floating,
            ),
          ),
          themeMode: useDarkMode ? ThemeMode.dark : ThemeMode.light,
          home: const RateLimitListener(child: MainScreen()),
        );
      },
      loading: () => MaterialApp(
        title: 'Filmmaker Alerts',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: const Scaffold(
          body: Center(child: CircularProgressIndicator()),
        ),
      ),
      error: (err, stack) => MaterialApp(
        title: 'Filmmaker Alerts',
        theme: ThemeData(
          colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
          useMaterial3: true,
        ),
        home: Scaffold(
          body: Center(child: Text('Error: $err')),
        ),
      ),
    );
  }
}