import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:workmanager/workmanager.dart';
import 'core/constants.dart';
import 'data/models/contributor.dart';
import 'data/models/movie_cache_entry.dart';
import 'data/models/tv_cache.dart';
import 'data/models/notification_history.dart';
import 'data/models/preferences.dart';
import 'ui/screens/main_screen.dart';
import 'ui/common/rate_limit_listener.dart';
import 'data/services/notification_service.dart';
import 'logic/background_service.dart';
import 'package:flutter_phoenix/flutter_phoenix.dart';
import 'providers/providers.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 0. Load Environment Variables
  await dotenv.load(fileName: ".env");

  // 1. Initialize Hive
  await Hive.initFlutter();

  // 2. Register Adapters (Generated by build_runner)
  Hive.registerAdapter(ContributorAdapter());
  Hive.registerAdapter(ContributorTypeAdapter());
  Hive.registerAdapter(TvNotificationPreferencesAdapter());
  Hive.registerAdapter(LatestWorkAdapter());
  Hive.registerAdapter(PreferencesAdapter());
  Hive.registerAdapter(NotificationHistoryEntryAdapter());
  Hive.registerAdapter(NotificationReasonAdapter());
  Hive.registerAdapter(NotificationEventAdapter());
  Hive.registerAdapter(MovieCacheEntryAdapter());
  Hive.registerAdapter(TvShowCacheEntryAdapter());
  Hive.registerAdapter(TvEpisodeCacheEntryAdapter());

  // 3. Open Boxes
  await Hive.openBox<Contributor>(AppConstants.contributorsBox);
  await Hive.openBox<Preferences>(AppConstants.preferencesBox);
  await Hive.openBox<NotificationHistoryEntry>(AppConstants.historyBox);
  await Hive.openBox<MovieCacheEntry>(AppConstants.movieCacheBox);

  // 4. Initialize Riverpod Container
  final container = ProviderContainer();

  // 5. Initialize TV Cache Repository
  final tvCacheRepo = container.read(tvCacheRepositoryProvider);
  await tvCacheRepo.init();

  // 6. Initialize Notification Service with callback for navigation
  final notificationService = container.read(notificationServiceProvider);
  await notificationService.init(
    onAction: (payload) {
      if (payload == 'app://history') {
        // Navigate to history tab
        container.read(selectedTabProvider.notifier).state = 1; // History tab index
      }
    },
  );

  // 7. Initialize Workmanager (Mobile only)
  if (!kIsWeb && (Platform.isAndroid || Platform.isIOS)) {
    await Workmanager().initialize(
      callbackDispatcher,
      isInDebugMode: kDebugMode,
    );
    
    // Calculate initial delay for 9:00 AM
    final now = DateTime.now();
    var firstRun = DateTime(now.year, now.month, now.day, 9, 0);
    if (firstRun.isBefore(now)) {
      firstRun = firstRun.add(const Duration(days: 1));
    }
    final initialDelay = firstRun.difference(now);

    await Workmanager().registerPeriodicTask(
      "daily-check-task",
      taskName,
      frequency: const Duration(hours: 24),
      initialDelay: initialDelay,
      constraints: Constraints(
        networkType: NetworkType.connected,
      ),
    );
  } else {
    debugPrint('[Main] Workmanager not supported on this platform. Background tasks skipped.');
  }

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: Phoenix(
        child: const MyApp(),
      ),
    ),
  );
}

class MyApp extends ConsumerWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    return MaterialApp(
      title: 'Filmmaker Alerts',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
        snackBarTheme: const SnackBarThemeData(
          behavior: SnackBarBehavior.floating,
          // 80 bottom padding ensures it floats above the FAB (approx 72px height w/ padding)
          insetPadding: EdgeInsets.fromLTRB(16, 0, 16, 80),
        ),
      ),
      // Main app screen
      home: const RateLimitListener(child: MainScreen()),
    );
  }
}