import 'dart:io';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:workmanager/workmanager.dart';
import 'package:window_manager/window_manager.dart';
import 'package:google_fonts/google_fonts.dart';
import 'core/constants.dart';
import 'data/models/contributor.dart';
import 'data/models/contributor_detail.dart';
import 'data/models/movie_detail.dart';
import 'data/models/movie_cache_entry.dart';
import 'data/models/tv_cache.dart';
import 'data/models/notification_history.dart';
import 'data/models/preferences.dart';
import 'data/models/tv_detail.dart';
import 'data/models/watchlist_entry.dart';
import 'data/models/status_record.dart';
import 'data/models/episode_status_entry.dart';
import 'data/models/season_status_entry.dart';
import 'data/models/movie_status_entry.dart';
import 'data/models/collection_order.dart';
import 'ui/screens/main_screen.dart';
import 'data/repositories/contributor_detail_repository.dart';
import 'ui/common/rate_limit_listener.dart';
import 'logic/background_service.dart';
import 'logic/single_instance_manager.dart';
import 'providers/providers.dart';
import 'package:path_provider/path_provider.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Check for single instance lock
  final canRun = await SingleInstanceManager.acquireLock();
  if (!canRun) {
    exit(1);
  }

  // Configure image cache to prevent unbounded memory growth
  imageCache.maximumSize = 100; // Maximum number of images to cache
  imageCache.maximumSizeBytes = 50 * 1024 * 1024; // 50MB maximum cache size

  // Reduce GC pressure by being more aggressive with memory cleanup
  // This helps prevent the 4-second freeze after idle
  imageCache.clear();
  imageCache.clearLiveImages();

  // 0. Initialize window manager (Windows only)
  if (Platform.isWindows) {
    await windowManager.ensureInitialized();
    
    WindowOptions windowOptions = const WindowOptions(
      size: Size(1280, 720),
      minimumSize: Size(400, 500),
      center: true,
      backgroundColor: Colors.transparent,
      skipTaskbar: false,
      titleBarStyle: TitleBarStyle.normal,
    );
    
    windowManager.waitUntilReadyToShow(windowOptions, () async {
      await windowManager.show();
      await windowManager.focus();
      
      // Set prevent close to true from the start
      await windowManager.setPreventClose(true);
    });
  }

  // 1. Load Environment Variables
  await dotenv.load(fileName: ".env");

  // 2. Initialize Hive
  if (Platform.isWindows) {
    final appSupportDir = await getApplicationSupportDirectory();
    await Hive.initFlutter(appSupportDir.path);
  } else {
    await Hive.initFlutter();
  }

  // 3. Register Adapters (Generated by build_runner)
  Hive.registerAdapter(ContributorAdapter());
  Hive.registerAdapter(ContributorTypeAdapter());
  Hive.registerAdapter(TvNotificationPreferencesAdapter());
  Hive.registerAdapter(LatestWorkAdapter());
  Hive.registerAdapter(PreferencesAdapter());
  Hive.registerAdapter(NotificationHistoryEntryAdapter());
  Hive.registerAdapter(NotificationReasonAdapter());
  Hive.registerAdapter(NotificationEventAdapter());
  Hive.registerAdapter(MovieCacheEntryAdapter());
  Hive.registerAdapter(TvShowCacheEntryAdapter());
  Hive.registerAdapter(TvEpisodeCacheEntryAdapter());
  
  // Register new contributor details adapters
  Hive.registerAdapter(WorkTypeAdapter());
  Hive.registerAdapter(ReleaseTypeAdapter());
  Hive.registerAdapter(StreamingTypeAdapter());
  Hive.registerAdapter(ContributorRoleAdapter());
  Hive.registerAdapter(StreamingOptionAdapter());
  Hive.registerAdapter(WorkAdapter());
  Hive.registerAdapter(ContributorDetailAdapter());
  Hive.registerAdapter(CastMemberAdapter());
  Hive.registerAdapter(CrewMemberAdapter());
  Hive.registerAdapter(MovieDetailAdapter());
  Hive.registerAdapter(TvShowDetailAdapter());
  Hive.registerAdapter(TvSeasonAdapter());
  Hive.registerAdapter(TvEpisodeDetailAdapter());
  Hive.registerAdapter(TvSeasonDetailAdapter());
  Hive.registerAdapter(SeasonEpisodeAdapter());

  // Register watchlist adapters
  Hive.registerAdapter(WatchlistEntryAdapter());
  Hive.registerAdapter(ContributorSnapshotAdapter());
  Hive.registerAdapter(ReleaseNotificationPreferencesAdapter());
  Hive.registerAdapter(StatusRecordAdapter());
  Hive.registerAdapter(WatchStatusAdapter());
  Hive.registerAdapter(EpisodeStatusEntryAdapter());
  Hive.registerAdapter(SeasonStatusEntryAdapter());
  Hive.registerAdapter(MovieStatusEntryAdapter());
  Hive.registerAdapter(CollectionOrderAdapter());

  // 4. Open Boxes with error handling for lock conflicts
  try {
    await _openHiveBoxes();

    // Migrate ContributorDetailRepository to string keys (one-time).
    // Must run after boxes are open — skip silently if boxes failed to open.
    final detailRepo = ContributorDetailRepository();
    await detailRepo.migrateToStringKeys();
  } catch (e) {
    // Continue anyway - the app will show an error dialog when it tries to access data
    // This allows the UI to load and display a helpful error message
  }

  // 5. Initialize Riverpod Container
  final container = ProviderContainer();

  // 6. Initialize TV Cache Repository
  final tvCacheRepo = container.read(tvCacheRepositoryProvider);
  await tvCacheRepo.init();

  // 7. Initialize Notification Service with callback for navigation
  final notificationService = container.read(notificationServiceProvider);
  await notificationService.init(
    onAction: (payload) {
      if (payload == 'app://history') {
        // Navigate to history tab
        container.read(selectedTabProvider.notifier).setTab(2); // History tab index
      }
    },
  );

  // 8. Initialize System Tray (Windows only)
  if (Platform.isWindows) {
    final systemTrayService = container.read(systemTrayServiceProvider);
    systemTrayService.setContainer(container); // Pass the container for release checking
    await systemTrayService.init();
  }

  if (!kIsWeb && (Platform.isAndroid || Platform.isIOS)) {
    await Workmanager().initialize(
      callbackDispatcher,
      // Note: isInDebugMode is deprecated but we keep it for backward compatibility
      // The parameter has no effect in newer versions
    );
    
    // Get user's scheduled notification time from preferences
    final prefsBox = Hive.box<Preferences>(AppConstants.preferencesBox);
    final prefs = prefsBox.isEmpty ? Preferences() : prefsBox.getAt(0)!;
    
    // Parse schedule time (format: "HH:MM")
    int scheduleHour = 9;
    int scheduleMinute = 0;
    try {
      final parts = prefs.scheduleTime.split(':');
      if (parts.length == 2) {
        scheduleHour = int.parse(parts[0]);
        scheduleMinute = int.parse(parts[1]);
      }
    } catch (e) {
    }
    
    // Calculate initial delay for the scheduled time
    final now = DateTime.now();
    var firstRun = DateTime(now.year, now.month, now.day, scheduleHour, scheduleMinute);
    if (firstRun.isBefore(now)) {
      firstRun = firstRun.add(const Duration(days: 1));
    }
    final initialDelay = firstRun.difference(now);

    await Workmanager().registerPeriodicTask(
      "daily-check-task",
      taskName,
      frequency: const Duration(hours: 24),
      initialDelay: initialDelay,
      constraints: Constraints(
        networkType: NetworkType.connected,
      ),
    );
  }

  // Read initial animation preference (won't change until restart)
  final prefsRepo = container.read(preferencesRepositoryProvider);
  final initialReduceAnimations = prefsRepo.getPreferences().reduceAnimations ?? false;

  runApp(
    UncontrolledProviderScope(
      container: container,
      child: MyApp(reduceAnimations: initialReduceAnimations),
    ),
  );
}

/// Opens all Hive boxes with retry logic for lock conflicts
Future<void> _openHiveBoxes() async {
  const maxRetries = 3;
  const retryDelay = Duration(milliseconds: 500);
  
  final boxes = [
    (AppConstants.contributorsBox, Contributor),
    (AppConstants.preferencesBox, Preferences),
    (AppConstants.historyBox, NotificationHistoryEntry),
    (AppConstants.movieCacheBox, MovieCacheEntry),
    (AppConstants.contributorDetailsBox, ContributorDetail),
    (AppConstants.movieDetailsBox, MovieDetail),
    (AppConstants.tvDetailsBox, TvShowDetail),
    (AppConstants.tvEpisodeDetailsBox, TvEpisodeDetail),
    (AppConstants.tvSeasonDetailsBox, TvSeasonDetail),
    (AppConstants.watchlistEntriesBox, WatchlistEntry),
    (AppConstants.episodeStatusesBox, EpisodeStatusEntry),
    (AppConstants.seasonStatusesBox, SeasonStatusEntry),
    (AppConstants.movieStatusesBox, MovieStatusEntry),
    (AppConstants.collectionOrdersBox, CollectionOrder),
  ];

  for (final (boxName, _) in boxes) {
    int retryCount = 0;
    while (retryCount < maxRetries) {
      try {
        // Use dynamic typing to open boxes without needing specific type info
        if (boxName == AppConstants.contributorsBox) {
          await Hive.openBox<Contributor>(boxName);
        } else if (boxName == AppConstants.preferencesBox) {
          await Hive.openBox<Preferences>(boxName);
        } else if (boxName == AppConstants.historyBox) {
          await Hive.openBox<NotificationHistoryEntry>(boxName);
        } else if (boxName == AppConstants.movieCacheBox) {
          await Hive.openBox<MovieCacheEntry>(boxName);
        } else if (boxName == AppConstants.contributorDetailsBox) {
          await Hive.openBox<ContributorDetail>(boxName);
        } else if (boxName == AppConstants.movieDetailsBox) {
          await Hive.openBox<MovieDetail>(boxName);
        } else if (boxName == AppConstants.tvDetailsBox) {
          await Hive.openBox<TvShowDetail>(boxName);
        } else if (boxName == AppConstants.tvEpisodeDetailsBox) {
          await Hive.openBox<TvEpisodeDetail>(boxName);
        } else if (boxName == AppConstants.tvSeasonDetailsBox) {
          await Hive.openBox<TvSeasonDetail>(boxName);
        } else if (boxName == AppConstants.watchlistEntriesBox) {
          await Hive.openBox<WatchlistEntry>(boxName);
        } else if (boxName == AppConstants.episodeStatusesBox) {
          await Hive.openBox<EpisodeStatusEntry>(boxName);
        } else if (boxName == AppConstants.seasonStatusesBox) {
          await Hive.openBox<SeasonStatusEntry>(boxName);
        } else if (boxName == AppConstants.movieStatusesBox) {
          await Hive.openBox<MovieStatusEntry>(boxName);
        } else if (boxName == AppConstants.collectionOrdersBox) {
          await Hive.openBox<CollectionOrder>(boxName);
        }
        
        break; // Success, move to next box
      } catch (e) {
        retryCount++;
        if (retryCount >= maxRetries) {
          rethrow; // Give up after max retries
        }
        await Future.delayed(retryDelay);
      }
    }
  }
}

/// Page transition builder that shows no animation
class _NoTransitionBuilder extends PageTransitionsBuilder {
  const _NoTransitionBuilder();

  @override
  Widget buildTransitions<T>(
    PageRoute<T> route,
    BuildContext context,
    Animation<double> animation,
    Animation<double> secondaryAnimation,
    Widget child,
  ) {
    return child;
  }
}

class MyApp extends ConsumerWidget {
  final bool reduceAnimations;
  
  const MyApp({super.key, required this.reduceAnimations});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final prefsAsync = ref.watch(preferencesProvider);
    
    // Kumbh Sans text theme - Regular weight for body, SemiBold for titles
    final kumbhTextTheme = GoogleFonts.kumbhSansTextTheme();
    
    // Use the startup value for animations (requires restart to change)
    // Page transitions theme - no animations when reduced
    final pageTransitionsTheme = reduceAnimations
        ? const PageTransitionsTheme(
            builders: {
              TargetPlatform.android: _NoTransitionBuilder(),
              TargetPlatform.iOS: _NoTransitionBuilder(),
              TargetPlatform.linux: _NoTransitionBuilder(),
              TargetPlatform.macOS: _NoTransitionBuilder(),
              TargetPlatform.windows: _NoTransitionBuilder(),
            },
          )
        : null;
    
    Widget app = MaterialApp(
      title: 'Filmmaker Alerts',
      theme: ThemeData(
        // Light mode - blue palette
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF007acc), // Classic blue
          brightness: Brightness.light,
        ),
        useMaterial3: true,
        textTheme: kumbhTextTheme,
        snackBarTheme: const SnackBarThemeData(
          behavior: SnackBarBehavior.floating,
        ),
        pageTransitionsTheme: pageTransitionsTheme,
      ),
      darkTheme: ThemeData(
        // Dark mode - universally appealing blue palette
        colorScheme: const ColorScheme.dark(
          brightness: Brightness.dark,
          // Primary - soft blue (easy on eyes, universally liked)
          primary: Color(0xFF4dabf7),           // Soft blue
          onPrimary: Color(0xFF0a0a0a),
          primaryContainer: Color(0xFF1a3a5c),  // Deep blue
          onPrimaryContainer: Color(0xFFa5d8ff),
          // Secondary - lighter blue accent
          secondary: Color(0xFF74c0fc),         // Light blue
          onSecondary: Color(0xFF0a0a0a),
          secondaryContainer: Color(0xFF1c3d5a),
          onSecondaryContainer: Color(0xFFd0ebff),
          // Tertiary - cyan/teal for variety
          tertiary: Color(0xFF38d9a9),          // Soft teal
          onTertiary: Color(0xFF0a0a0a),
          tertiaryContainer: Color(0xFF1a3d35),
          onTertiaryContainer: Color(0xFF96f2d7),
          // Error
          error: Color(0xFFff8787),
          onError: Color(0xFF0a0a0a),
          errorContainer: Color(0xFF4d3030),
          onErrorContainer: Color(0xFFffc9c9),
          // Surfaces - very dark backgrounds
          surface: Color(0xFF141414),
          onSurface: Color(0xFFF2F2F2),
          surfaceContainerHighest: Color(0xFF2a2a2a),
          onSurfaceVariant: Color(0xFFb3b3b3),
          outline: Color(0xFF4d4d4d),
          outlineVariant: Color(0xFF404040),
          shadow: Color(0xFF000000),
          scrim: Color(0xFF000000),
          inverseSurface: Color(0xFFF2F2F2),
          onInverseSurface: Color(0xFF171717),
          inversePrimary: Color(0xFF1971c2),
          surfaceTint: Color(0xFF4dabf7),
        ),
        scaffoldBackgroundColor: const Color(0xFF0f0f0f), // Darker background for more contrast
        cardColor: const Color(0xFF2a2a2a),     // Lighter card for better contrast
        dividerColor: const Color(0xFF4d4d4d),  // borders
        // Kumbh Sans with bright text colors for dark mode
        textTheme: GoogleFonts.kumbhSansTextTheme(
          const TextTheme(
            // Display styles - SemiBold
            displayLarge: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w600),
            displayMedium: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w600),
            displaySmall: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w600),
            // Headline styles - SemiBold
            headlineLarge: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w600),
            headlineMedium: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w600),
            headlineSmall: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w600),
            // Title styles - Medium
            titleLarge: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w500),
            titleMedium: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w500),
            titleSmall: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w500),
            // Body styles - Regular
            bodyLarge: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w400),
            bodyMedium: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w400),
            bodySmall: TextStyle(color: Color(0xFFb3b3b3), fontWeight: FontWeight.w400),
            // Label styles - Regular
            labelLarge: TextStyle(color: Color(0xFFF2F2F2), fontWeight: FontWeight.w400),
            labelMedium: TextStyle(color: Color(0xFFb3b3b3), fontWeight: FontWeight.w400),
            labelSmall: TextStyle(color: Color(0xFFb3b3b3), fontWeight: FontWeight.w400),
          ),
        ),
        useMaterial3: true,
        snackBarTheme: const SnackBarThemeData(
          behavior: SnackBarBehavior.floating,
        ),
        pageTransitionsTheme: pageTransitionsTheme,
      ),
      themeMode: prefsAsync.maybeWhen(
        data: (prefs) => prefs.useDarkMode ?? true ? ThemeMode.dark : ThemeMode.light,
        orElse: () => ThemeMode.dark,
      ),
      home: prefsAsync.when(
        data: (prefs) {
          return _AppLifecycleWrapper(
            child: RateLimitListener(child: MainScreen()),
          );
        },
        loading: () => const Scaffold(
          body: Center(child: CircularProgressIndicator()),
        ),
        error: (err, stack) {
          // Check if it's a Hive lock error
          final isLockError = err.toString().contains('lock failed') || 
                              err.toString().contains('PathAccessException');
          
          return Scaffold(
            body: Center(
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    const Icon(Icons.error_outline, size: 64, color: Colors.red),
                    const SizedBox(height: 24),
                    const Text(
                      'Database Error',
                      style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                    ),
                    const SizedBox(height: 16),
                    if (isLockError) ...[
                      const Text(
                        'The app database is locked. This usually happens when multiple instances of the app are running.',
                        textAlign: TextAlign.center,
                        style: TextStyle(fontSize: 16),
                      ),
                      const SizedBox(height: 16),
                      const Text(
                        'Please close all other instances of Filmmaker Alerts and restart the app.',
                        textAlign: TextAlign.center,
                        style: TextStyle(fontSize: 14, color: Colors.grey),
                      ),
                    ] else ...[
                      Text(
                        'An error occurred while loading the app: $err',
                        textAlign: TextAlign.center,
                        style: const TextStyle(fontSize: 14),
                      ),
                    ],
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: () {
                        // Restart the app by exiting
                        exit(0);
                      },
                      child: const Text('Exit App'),
                    ),
                  ],
                ),
              ),
            ),
          );
        },
      ),
    );
    
    // Wrap with MediaQuery to disable animations when preference is set
    if (reduceAnimations) {
      return MediaQuery(
        data: MediaQueryData.fromView(WidgetsBinding.instance.platformDispatcher.views.first).copyWith(
          disableAnimations: true,
        ),
        child: app,
      );
    }
    
    return app;
  }
}

/// Wrapper to handle app lifecycle and clear caches on resume
class _AppLifecycleWrapper extends ConsumerStatefulWidget {
  final Widget child;

  const _AppLifecycleWrapper({required this.child});

  @override
  ConsumerState<_AppLifecycleWrapper> createState() => _AppLifecycleWrapperState();
}

class _AppLifecycleWrapperState extends ConsumerState<_AppLifecycleWrapper>
    with WidgetsBindingObserver {
  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);

    // Upload whenever the watchlist changes (add, remove, status change, rating).
    // Registered synchronously so no changes are missed.
    // uploadIfSignedIn() is a no-op when _isApplyingDownload is true,
    // preventing an echo upload after a download replaces the watchlist.
    ref.listenManual(watchlistEntriesProvider, (_, __) {
      ref.read(syncServiceProvider).uploadIfSignedIn();
    });

    // Try to restore Google session and download newer data on launch.
    WidgetsBinding.instance.addPostFrameCallback((_) async {
      final auth = ref.read(googleAuthServiceProvider);
      final restored = await auth.tryRestoreSession();
      if (restored) {
        await _downloadAndRefreshIfNewer();
      }
    });
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    // Note: do NOT call uploadIfSignedIn() here — dispose() is synchronous,
    // the Future would be abandoned before Hive boxes close.
    // Upload is handled by AppLifecycleState.paused (mobile) and
    // AppLifecycleState.detached (both platforms) in didChangeAppLifecycleState.
    _closeHiveBoxes();
    _releaseSingleInstanceLock();
    super.dispose();
  }

  /// Releases the single-instance lock
  Future<void> _releaseSingleInstanceLock() async {
    await SingleInstanceManager.releaseLock();
  }

  /// Properly close all Hive boxes to release locks
  Future<void> _closeHiveBoxes() async {
    try {
      await Hive.close();
    } catch (e) {
    }
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
      // Clear image cache when app resumes to prevent GC pause
      imageCache.clear();
      imageCache.clearLiveImages();

      // Invalidate cached data providers so fresh data is read from Hive
      ref.invalidate(contributorsProvider);
      ref.invalidate(watchlistEntriesProvider);
      ref.invalidate(connectionsDataProvider);

      // Download newer sync data on foreground then refresh UI if replaced
      _downloadAndRefreshIfNewer();
    } else if (state == AppLifecycleState.paused) {
      // Upload on background — paused fires while the process is still alive,
      // giving enough time for the async upload to complete.
      ref.read(syncServiceProvider).uploadIfSignedIn();
    } else if (state == AppLifecycleState.detached) {
      // paused already handles upload; detached fires too late on Android
      // for async work to complete reliably.
      _closeHiveBoxes();
      _releaseSingleInstanceLock();
    }
  }

  /// Downloads from Drive if remote is newer, then invalidates providers
  /// so the UI reflects the new data without requiring a restart.
  Future<void> _downloadAndRefreshIfNewer() async {
    final wasReplaced =
        await ref.read(syncServiceProvider).downloadIfNewerAndSignedIn();
    if (wasReplaced && mounted) {
      ref.invalidate(watchlistEntriesProvider);
      ref.invalidate(contributorsProvider);
      ref.invalidate(preferencesProvider);
      ref.invalidate(connectionsDataProvider);
    }
  }

  @override
  Widget build(BuildContext context) => widget.child;
}
