// Mocks generated by Mockito 5.4.4 from annotations
// in filmmaker_alerts/test/ui/show_configuration_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:filmmaker_alerts/data/models/contributor.dart' as _i13;
import 'package:filmmaker_alerts/data/models/contributor_detail.dart' as _i12;
import 'package:filmmaker_alerts/data/models/episode_status_entry.dart' as _i2;
import 'package:filmmaker_alerts/data/models/movie_detail.dart' as _i15;
import 'package:filmmaker_alerts/data/models/season_status_entry.dart' as _i3;
import 'package:filmmaker_alerts/data/models/status_record.dart' as _i7;
import 'package:filmmaker_alerts/data/models/tv_detail.dart' as _i10;
import 'package:filmmaker_alerts/data/models/watchlist_entry.dart' as _i4;
import 'package:filmmaker_alerts/data/repositories/episode_status_repository.dart'
    as _i5;
import 'package:filmmaker_alerts/data/repositories/season_status_repository.dart'
    as _i8;
import 'package:filmmaker_alerts/data/repositories/tv_detail_repository.dart'
    as _i9;
import 'package:filmmaker_alerts/logic/watchlist_logic.dart' as _i11;
import 'package:filmmaker_alerts/logic/work_logic.dart' as _i14;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEpisodeStatusEntry_0 extends _i1.SmartFake
    implements _i2.EpisodeStatusEntry {
  _FakeEpisodeStatusEntry_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSeasonStatusEntry_1 extends _i1.SmartFake
    implements _i3.SeasonStatusEntry {
  _FakeSeasonStatusEntry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWatchlistEntry_2 extends _i1.SmartFake
    implements _i4.WatchlistEntry {
  _FakeWatchlistEntry_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EpisodeStatusRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockEpisodeStatusRepository extends _i1.Mock
    implements _i5.EpisodeStatusRepository {
  MockEpisodeStatusRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.EpisodeStatusEntry> getOrCreateEpisode({
    required int? showId,
    required int? seasonNumber,
    required int? episodeNumber,
    required String? episodeTitle,
    DateTime? airDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateEpisode,
          [],
          {
            #showId: showId,
            #seasonNumber: seasonNumber,
            #episodeNumber: episodeNumber,
            #episodeTitle: episodeTitle,
            #airDate: airDate,
          },
        ),
        returnValue:
            _i6.Future<_i2.EpisodeStatusEntry>.value(_FakeEpisodeStatusEntry_0(
          this,
          Invocation.method(
            #getOrCreateEpisode,
            [],
            {
              #showId: showId,
              #seasonNumber: seasonNumber,
              #episodeNumber: episodeNumber,
              #episodeTitle: episodeTitle,
              #airDate: airDate,
            },
          ),
        )),
      ) as _i6.Future<_i2.EpisodeStatusEntry>);

  @override
  _i2.EpisodeStatusEntry? getEpisode(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getEpisode,
        [
          showId,
          seasonNumber,
          episodeNumber,
        ],
      )) as _i2.EpisodeStatusEntry?);

  @override
  List<_i2.EpisodeStatusEntry> getEpisodesByShow(int? showId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesByShow,
          [showId],
        ),
        returnValue: <_i2.EpisodeStatusEntry>[],
      ) as List<_i2.EpisodeStatusEntry>);

  @override
  List<_i2.EpisodeStatusEntry> getEpisodesBySeason(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesBySeason,
          [
            showId,
            seasonNumber,
          ],
        ),
        returnValue: <_i2.EpisodeStatusEntry>[],
      ) as List<_i2.EpisodeStatusEntry>);

  @override
  _i6.Future<void> addStatusRecord(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
    _i7.StatusRecord? record,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStatusRecord,
          [
            showId,
            seasonNumber,
            episodeNumber,
            record,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateEpisode(_i2.EpisodeStatusEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEpisode,
          [entry],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteEpisode(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEpisode,
          [
            showId,
            seasonNumber,
            episodeNumber,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [SeasonStatusRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSeasonStatusRepository extends _i1.Mock
    implements _i8.SeasonStatusRepository {
  MockSeasonStatusRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.SeasonStatusEntry> getOrCreateSeason({
    required int? showId,
    required int? seasonNumber,
    DateTime? airDate,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getOrCreateSeason,
          [],
          {
            #showId: showId,
            #seasonNumber: seasonNumber,
            #airDate: airDate,
          },
        ),
        returnValue:
            _i6.Future<_i3.SeasonStatusEntry>.value(_FakeSeasonStatusEntry_1(
          this,
          Invocation.method(
            #getOrCreateSeason,
            [],
            {
              #showId: showId,
              #seasonNumber: seasonNumber,
              #airDate: airDate,
            },
          ),
        )),
      ) as _i6.Future<_i3.SeasonStatusEntry>);

  @override
  _i3.SeasonStatusEntry? getSeason(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getSeason,
        [
          showId,
          seasonNumber,
        ],
      )) as _i3.SeasonStatusEntry?);

  @override
  List<_i3.SeasonStatusEntry> getSeasonsByShow(int? showId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSeasonsByShow,
          [showId],
        ),
        returnValue: <_i3.SeasonStatusEntry>[],
      ) as List<_i3.SeasonStatusEntry>);

  @override
  _i6.Future<void> addStatusRecord(
    int? showId,
    int? seasonNumber,
    _i7.StatusRecord? record,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStatusRecord,
          [
            showId,
            seasonNumber,
            record,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateSeason(_i3.SeasonStatusEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateSeason,
          [entry],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteSeason(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteSeason,
          [
            showId,
            seasonNumber,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [TvDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailRepository extends _i1.Mock
    implements _i9.TvDetailRepository {
  MockTvDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.TvShowDetail? getTvShowDetail(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getTvShowDetail,
        [tmdbId],
      )) as _i10.TvShowDetail?);

  @override
  _i6.Future<void> cacheTvShowDetail(_i10.TvShowDetail? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTvShowDetail,
          [detail],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool isShowCached(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #isShowCached,
          [tmdbId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.TvSeasonDetail? getTvSeasonDetail(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getTvSeasonDetail,
        [
          showId,
          seasonNumber,
        ],
      )) as _i10.TvSeasonDetail?);

  @override
  _i10.TvSeasonDetail? getTvSeasonDetailExplicit(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getTvSeasonDetailExplicit,
        [
          showId,
          seasonNumber,
        ],
      )) as _i10.TvSeasonDetail?);

  @override
  _i6.Future<void> cacheTvSeasonDetail(_i10.TvSeasonDetail? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTvSeasonDetail,
          [detail],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool isSeasonCached(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isSeasonCached,
          [
            showId,
            seasonNumber,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i10.TvEpisodeDetail? getTvEpisodeDetail(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getTvEpisodeDetail,
        [tmdbId],
      )) as _i10.TvEpisodeDetail?);

  @override
  _i6.Future<void> cacheTvEpisodeDetail(_i10.TvEpisodeDetail? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTvEpisodeDetail,
          [detail],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool isEpisodeCached(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #isEpisodeCached,
          [tmdbId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i6.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [WatchlistLogic].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistLogic extends _i1.Mock implements _i11.WatchlistLogic {
  MockWatchlistLogic() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.WatchlistEntry> addWorkToWatchlist({
    required int? tmdbId,
    required _i12.WorkType? type,
    required String? title,
    String? posterPath,
    DateTime? releaseDate,
    _i12.ReleaseType? releaseType,
    List<_i4.ContributorSnapshot>? followedContributors,
    _i4.ReleaseNotificationPreferences? releaseNotificationPrefs,
    _i13.TvNotificationPreferences? tvNotificationPrefs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWorkToWatchlist,
          [],
          {
            #tmdbId: tmdbId,
            #type: type,
            #title: title,
            #posterPath: posterPath,
            #releaseDate: releaseDate,
            #releaseType: releaseType,
            #followedContributors: followedContributors,
            #releaseNotificationPrefs: releaseNotificationPrefs,
            #tvNotificationPrefs: tvNotificationPrefs,
          },
        ),
        returnValue: _i6.Future<_i4.WatchlistEntry>.value(_FakeWatchlistEntry_2(
          this,
          Invocation.method(
            #addWorkToWatchlist,
            [],
            {
              #tmdbId: tmdbId,
              #type: type,
              #title: title,
              #posterPath: posterPath,
              #releaseDate: releaseDate,
              #releaseType: releaseType,
              #followedContributors: followedContributors,
              #releaseNotificationPrefs: releaseNotificationPrefs,
              #tvNotificationPrefs: tvNotificationPrefs,
            },
          ),
        )),
      ) as _i6.Future<_i4.WatchlistEntry>);

  @override
  _i6.Future<void> removeWorkFromWatchlist(
    int? tmdbId,
    _i12.WorkType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWorkFromWatchlist,
          [
            tmdbId,
            type,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<_i4.WatchlistEntry> getWatchlistWorks() => (super.noSuchMethod(
        Invocation.method(
          #getWatchlistWorks,
          [],
        ),
        returnValue: <_i4.WatchlistEntry>[],
      ) as List<_i4.WatchlistEntry>);

  @override
  List<_i4.WatchlistEntry> getWorksByType(_i12.WorkType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorksByType,
          [type],
        ),
        returnValue: <_i4.WatchlistEntry>[],
      ) as List<_i4.WatchlistEntry>);

  @override
  _i6.Future<bool> isWorkInWatchlist(
    int? tmdbId,
    _i12.WorkType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isWorkInWatchlist,
          [
            tmdbId,
            type,
          ],
        ),
        returnValue: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i4.WatchlistEntry? getWork(
    int? tmdbId,
    _i12.WorkType? type,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getWork,
        [
          tmdbId,
          type,
        ],
      )) as _i4.WatchlistEntry?);

  @override
  _i6.Future<void> addStatusToWork(
    int? tmdbId,
    _i12.WorkType? type,
    _i7.WatchStatus? status, {
    List<DateTime>? watchDates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStatusToWork,
          [
            tmdbId,
            type,
            status,
          ],
          {#watchDates: watchDates},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeStatusFromWork(
    int? tmdbId,
    _i12.WorkType? type,
    _i7.WatchStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeStatusFromWork,
          [
            tmdbId,
            type,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setSnoozed(
    int? tmdbId,
    _i12.WorkType? type,
    bool? snoozed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSnoozed,
          [
            tmdbId,
            type,
            snoozed,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setNotificationsSnoozed(
    int? tmdbId,
    _i12.WorkType? type,
    bool? snoozed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsSnoozed,
          [
            tmdbId,
            type,
            snoozed,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateUserRank(
    int? tmdbId,
    _i12.WorkType? type,
    int? rank,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserRank,
          [
            tmdbId,
            type,
            rank,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateContributorSnapshot(
    int? tmdbId,
    _i12.WorkType? type,
    List<_i4.ContributorSnapshot>? contributors,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContributorSnapshot,
          [
            tmdbId,
            type,
            contributors,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateReleaseNotificationPreferences(
    int? tmdbId,
    _i12.WorkType? type,
    _i4.ReleaseNotificationPreferences? preferences,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReleaseNotificationPreferences,
          [
            tmdbId,
            type,
            preferences,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateTvNotificationPreferences(
    int? tmdbId,
    _i13.TvNotificationPreferences? preferences,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTvNotificationPreferences,
          [
            tmdbId,
            preferences,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> updateAllContributorSnapshots(
          List<_i13.Contributor>? followedContributors) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateAllContributorSnapshots,
          [followedContributors],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addStatusToEpisode(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
    _i7.WatchStatus? status, {
    List<DateTime>? watchDates,
    String? episodeTitle,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStatusToEpisode,
          [
            showId,
            seasonNumber,
            episodeNumber,
            status,
          ],
          {
            #watchDates: watchDates,
            #episodeTitle: episodeTitle,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> removeStatusFromEpisode(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeStatusFromEpisode,
          [
            showId,
            seasonNumber,
            episodeNumber,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> addStatusToSeason(
    int? showId,
    int? seasonNumber,
    _i7.WatchStatus? status, {
    List<DateTime>? watchDates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStatusToSeason,
          [
            showId,
            seasonNumber,
            status,
          ],
          {#watchDates: watchDates},
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  List<dynamic> getEpisodesForShow(int? showId) => (super.noSuchMethod(
        Invocation.method(
          #getEpisodesForShow,
          [showId],
        ),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> getSeasonsForShow(int? showId) => (super.noSuchMethod(
        Invocation.method(
          #getSeasonsForShow,
          [showId],
        ),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  _i6.Future<void> markMultipleEpisodes(
    int? showId,
    List<Map<String, dynamic>>? episodes,
    _i7.WatchStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #markMultipleEpisodes,
          [
            showId,
            episodes,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [WorkLogic].
///
/// See the documentation for Mockito's code generation for more information.
class MockWorkLogic extends _i1.Mock implements _i14.WorkLogic {
  MockWorkLogic() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i15.MovieDetail?> fetchAndCacheMovieDetail(
    int? tmdbId, {
    String? regionCode = r'US',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAndCacheMovieDetail,
          [tmdbId],
          {#regionCode: regionCode},
        ),
        returnValue: _i6.Future<_i15.MovieDetail?>.value(),
      ) as _i6.Future<_i15.MovieDetail?>);

  @override
  _i6.Future<_i10.TvShowDetail?> fetchAndCacheTvShowDetail(
    int? tmdbId, {
    String? regionCode = r'US',
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAndCacheTvShowDetail,
          [tmdbId],
          {#regionCode: regionCode},
        ),
        returnValue: _i6.Future<_i10.TvShowDetail?>.value(),
      ) as _i6.Future<_i10.TvShowDetail?>);

  @override
  _i6.Future<_i10.TvEpisodeDetail?> fetchAndCacheTvEpisodeDetail({
    required int? showId,
    required int? seasonNumber,
    required int? episodeNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAndCacheTvEpisodeDetail,
          [],
          {
            #showId: showId,
            #seasonNumber: seasonNumber,
            #episodeNumber: episodeNumber,
          },
        ),
        returnValue: _i6.Future<_i10.TvEpisodeDetail?>.value(),
      ) as _i6.Future<_i10.TvEpisodeDetail?>);

  @override
  _i6.Future<_i10.TvSeasonDetail?> fetchAndCacheTvSeasonDetail({
    required int? showId,
    required int? seasonNumber,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchAndCacheTvSeasonDetail,
          [],
          {
            #showId: showId,
            #seasonNumber: seasonNumber,
          },
        ),
        returnValue: _i6.Future<_i10.TvSeasonDetail?>.value(),
      ) as _i6.Future<_i10.TvSeasonDetail?>);
}
