// Mocks generated by Mockito 5.4.4 from annotations
// in filmmaker_alerts/test/helpers/test_helpers.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:dio/dio.dart' as _i2;
import 'package:filmmaker_alerts/data/models/contributor.dart' as _i10;
import 'package:filmmaker_alerts/data/models/contributor_detail.dart' as _i19;
import 'package:filmmaker_alerts/data/models/movie_cache_entry.dart' as _i15;
import 'package:filmmaker_alerts/data/models/movie_detail.dart' as _i21;
import 'package:filmmaker_alerts/data/models/notification_history.dart' as _i13;
import 'package:filmmaker_alerts/data/models/preferences.dart' as _i3;
import 'package:filmmaker_alerts/data/models/status_record.dart' as _i27;
import 'package:filmmaker_alerts/data/models/tv_cache.dart' as _i17;
import 'package:filmmaker_alerts/data/models/tv_detail.dart' as _i23;
import 'package:filmmaker_alerts/data/models/watchlist_entry.dart' as _i4;
import 'package:filmmaker_alerts/data/repositories/contributor_detail_repository.dart'
    as _i18;
import 'package:filmmaker_alerts/data/repositories/contributor_repository.dart'
    as _i9;
import 'package:filmmaker_alerts/data/repositories/history_repository.dart'
    as _i12;
import 'package:filmmaker_alerts/data/repositories/movie_cache_repository.dart'
    as _i14;
import 'package:filmmaker_alerts/data/repositories/movie_detail_repository.dart'
    as _i20;
import 'package:filmmaker_alerts/data/repositories/preferences_repository.dart'
    as _i11;
import 'package:filmmaker_alerts/data/repositories/tv_cache_repository.dart'
    as _i16;
import 'package:filmmaker_alerts/data/repositories/tv_detail_repository.dart'
    as _i22;
import 'package:filmmaker_alerts/data/repositories/watchlist_repository.dart'
    as _i26;
import 'package:filmmaker_alerts/data/services/notification_service.dart'
    as _i24;
import 'package:filmmaker_alerts/data/services/tmdb_service.dart' as _i7;
import 'package:flutter/foundation.dart' as _i30;
import 'package:flutter_local_notifications/flutter_local_notifications.dart'
    as _i25;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i6;
import 'package:google_sign_in/google_sign_in.dart' as _i5;
import 'package:google_sign_in_platform_interface/google_sign_in_platform_interface.dart'
    as _i28;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i29;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreferences_1 extends _i1.SmartFake implements _i3.Preferences {
  _FakePreferences_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_2 extends _i1.SmartFake implements _i2.BaseOptions {
  _FakeBaseOptions_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_3 extends _i1.SmartFake
    implements _i2.HttpClientAdapter {
  _FakeHttpClientAdapter_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_4 extends _i1.SmartFake implements _i2.Transformer {
  _FakeTransformer_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_5 extends _i1.SmartFake implements _i2.Interceptors {
  _FakeInterceptors_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_6<T1> extends _i1.SmartFake implements _i2.Response<T1> {
  _FakeResponse_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWatchlistEntry_7 extends _i1.SmartFake
    implements _i4.WatchlistEntry {
  _FakeWatchlistEntry_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGoogleSignInAuthentication_8 extends _i1.SmartFake
    implements _i5.GoogleSignInAuthentication {
  _FakeGoogleSignInAuthentication_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIOSOptions_9 extends _i1.SmartFake implements _i6.IOSOptions {
  _FakeIOSOptions_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAndroidOptions_10 extends _i1.SmartFake
    implements _i6.AndroidOptions {
  _FakeAndroidOptions_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLinuxOptions_11 extends _i1.SmartFake implements _i6.LinuxOptions {
  _FakeLinuxOptions_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWindowsOptions_12 extends _i1.SmartFake
    implements _i6.WindowsOptions {
  _FakeWindowsOptions_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeWebOptions_13 extends _i1.SmartFake implements _i6.WebOptions {
  _FakeWebOptions_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAppleOptions_14 extends _i1.SmartFake implements _i6.AppleOptions {
  _FakeAppleOptions_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TmdbService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTmdbService extends _i1.Mock implements _i7.TmdbService {
  MockTmdbService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Stream<_i7.RateLimitEvent> get onRateLimit => (super.noSuchMethod(
        Invocation.getter(#onRateLimit),
        returnValue: _i8.Stream<_i7.RateLimitEvent>.empty(),
      ) as _i8.Stream<_i7.RateLimitEvent>);

  @override
  _i2.Dio get client => (super.noSuchMethod(
        Invocation.getter(#client),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#client),
        ),
      ) as _i2.Dio);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<Map<String, dynamic>> searchPerson(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchPerson,
          [query],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> searchCompany(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCompany,
          [query],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> searchMovie(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchMovie,
          [query],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> searchCollection(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchCollection,
          [query],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> searchTv(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchTv,
          [query],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> searchKeyword(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchKeyword,
          [query],
          {#page: page},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getKeywordDetails(int? keywordId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKeywordDetails,
          [keywordId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getKeywordWorks(
    int? keywordId,
    String? type, {
    String? since,
    int? page = 1,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKeywordWorks,
          [
            keywordId,
            type,
          ],
          {
            #since: since,
            #page: page,
          },
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getKeywordTopWorks(int? keywordId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getKeywordTopWorks,
          [keywordId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTrendingMovies() => (super.noSuchMethod(
        Invocation.method(
          #getTrendingMovies,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTrendingPeople() => (super.noSuchMethod(
        Invocation.method(
          #getTrendingPeople,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getPopularPeople() => (super.noSuchMethod(
        Invocation.method(
          #getPopularPeople,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getUpcomingMovies() => (super.noSuchMethod(
        Invocation.method(
          #getUpcomingMovies,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getPersonDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonDetails,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getPersonCombinedCredits(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPersonCombinedCredits,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getCompanyCredits(
    int? id,
    String? type, {
    String? since,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompanyCredits,
          [
            id,
            type,
          ],
          {#since: since},
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getCompanyTopWorks(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompanyTopWorks,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getCompanyUpcomingWorks(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompanyUpcomingWorks,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<dynamic>> filterToProductionOnly(
    List<dynamic>? discoverResults,
    int? companyId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterToProductionOnly,
          [
            discoverResults,
            companyId,
          ],
        ),
        returnValue: _i8.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i8.Future<List<dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getMovieDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieDetails,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getMovieCredits(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieCredits,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getCollectionDetails(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCollectionDetails,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvDetails(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvDetails,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvDetailsBasic(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetailsBasic,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvDetailsWithEpisodes(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetailsWithEpisodes,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvDetailsOptimized(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvDetailsOptimized,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<List<_i7.TvShowCandidate>> filterTvShowCandidates(
          List<int>? showIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterTvShowCandidates,
          [showIds],
        ),
        returnValue: _i8.Future<List<_i7.TvShowCandidate>>.value(
            <_i7.TvShowCandidate>[]),
      ) as _i8.Future<List<_i7.TvShowCandidate>>);

  @override
  _i8.Future<List<Map<String, dynamic>>> getTvNewEpisodesEfficient(
    int? showId,
    String? startDate,
    String? endDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvNewEpisodesEfficient,
          [
            showId,
            startDate,
            endDate,
          ],
        ),
        returnValue: _i8.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i8.Future<List<Map<String, dynamic>>>);

  @override
  _i8.Future<Map<String, dynamic>> getCreditDetails(String? creditId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCreditDetails,
          [creditId],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvSeasonDetails(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvSeasonDetails,
          [
            showId,
            seasonNumber,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvEpisodeDetails(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvEpisodeDetails,
          [
            showId,
            seasonNumber,
            episodeNumber,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvCredits(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getTvCredits,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvAggregateCredits(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvAggregateCredits,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvEpisodeCredits(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvEpisodeCredits,
          [
            showId,
            seasonNumber,
            episodeNumber,
          ],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getMovieWatchProviders(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovieWatchProviders,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvWatchProviders(int? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTvWatchProviders,
          [id],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getWatchProviderRegions() =>
      (super.noSuchMethod(
        Invocation.method(
          #getWatchProviderRegions,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvOnTheAir() => (super.noSuchMethod(
        Invocation.method(
          #getTvOnTheAir,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<Map<String, dynamic>> getTvAiringToday() => (super.noSuchMethod(
        Invocation.method(
          #getTvAiringToday,
          [],
        ),
        returnValue:
            _i8.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i8.Future<Map<String, dynamic>>);
}

/// A class which mocks [ContributorRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContributorRepository extends _i1.Mock
    implements _i9.ContributorRepository {
  MockContributorRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i10.Contributor> getContributors() => (super.noSuchMethod(
        Invocation.method(
          #getContributors,
          [],
        ),
        returnValue: <_i10.Contributor>[],
      ) as List<_i10.Contributor>);

  @override
  _i10.Contributor? getContributor(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getContributor,
        [tmdbId],
      )) as _i10.Contributor?);

  @override
  _i8.Future<bool> addContributor(_i10.Contributor? contributor) =>
      (super.noSuchMethod(
        Invocation.method(
          #addContributor,
          [contributor],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> updateContributor(_i10.Contributor? updatedContributor) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContributor,
          [updatedContributor],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeContributor(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #removeContributor,
          [tmdbId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isFollowed(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #isFollowed,
          [tmdbId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> setHidden(
    int? tmdbId,
    bool? hidden,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setHidden,
          [
            tmdbId,
            hidden,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [PreferencesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesRepository extends _i1.Mock
    implements _i11.PreferencesRepository {
  MockPreferencesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Preferences getPreferences() => (super.noSuchMethod(
        Invocation.method(
          #getPreferences,
          [],
        ),
        returnValue: _FakePreferences_1(
          this,
          Invocation.method(
            #getPreferences,
            [],
          ),
        ),
      ) as _i3.Preferences);

  @override
  _i8.Future<void> savePreferences(_i3.Preferences? prefs) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePreferences,
          [prefs],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i2.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_2(
          this,
          Invocation.getter(#options),
        ),
      ) as _i2.BaseOptions);

  @override
  set options(_i2.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_3(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i2.HttpClientAdapter);

  @override
  set httpClientAdapter(_i2.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_4(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i2.Transformer);

  @override
  set transformer(_i2.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_5(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i2.Interceptors);

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i2.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i2.Options? options,
    _i2.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = r'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i8.Future<_i2.Response<dynamic>>.value(_FakeResponse_6<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i2.ProgressCallback? onReceiveProgress,
    _i2.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i2.FileAccessMode? fileAccessMode = _i2.FileAccessMode.write,
    String? lengthHeader = r'content-length',
    Object? data,
    _i2.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #fileAccessMode: fileAccessMode,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i8.Future<_i2.Response<dynamic>>.value(_FakeResponse_6<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #fileAccessMode: fileAccessMode,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<dynamic>>);

  @override
  _i8.Future<_i2.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i2.CancelToken? cancelToken,
    _i2.Options? options,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i8.Future<_i2.Response<T>> fetch<T>(_i2.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i8.Future<_i2.Response<T>>.value(_FakeResponse_6<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i8.Future<_i2.Response<T>>);

  @override
  _i2.Dio clone({
    _i2.BaseOptions? options,
    _i2.Interceptors? interceptors,
    _i2.HttpClientAdapter? httpClientAdapter,
    _i2.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #clone,
          [],
          {
            #options: options,
            #interceptors: interceptors,
            #httpClientAdapter: httpClientAdapter,
            #transformer: transformer,
          },
        ),
        returnValue: _FakeDio_0(
          this,
          Invocation.method(
            #clone,
            [],
            {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            },
          ),
        ),
      ) as _i2.Dio);
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i12.HistoryRepository {
  MockHistoryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i12.EnrichedHistoryEntry> getHistory() => (super.noSuchMethod(
        Invocation.method(
          #getHistory,
          [],
        ),
        returnValue: <_i12.EnrichedHistoryEntry>[],
      ) as List<_i12.EnrichedHistoryEntry>);

  @override
  _i8.Future<void> addNotificationToHistory(
          _i13.NotificationHistoryEntry? newEntry) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNotificationToHistory,
          [newEntry],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool> removeNotificationFromHistory(int? tmdbId) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeNotificationFromHistory,
          [tmdbId],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> clearAllHistory() => (super.noSuchMethod(
        Invocation.method(
          #clearAllHistory,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [MovieCacheRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieCacheRepository extends _i1.Mock
    implements _i14.MovieCacheRepository {
  MockMovieCacheRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> addOrUpdateMovieInCache(_i15.MovieCacheEntry? entry) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrUpdateMovieInCache,
          [entry],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i15.MovieCacheEntry? getMovie(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getMovie,
        [tmdbId],
      )) as _i15.MovieCacheEntry?);
}

/// A class which mocks [TvCacheRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvCacheRepository extends _i1.Mock implements _i16.TvCacheRepository {
  MockTvCacheRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addOrUpdateShow(_i17.TvShowCacheEntry? show) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrUpdateShow,
          [show],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i17.TvShowCacheEntry? getShow(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getShow,
        [tmdbId],
      )) as _i17.TvShowCacheEntry?);

  @override
  List<_i17.TvShowCacheEntry> getAllShows() => (super.noSuchMethod(
        Invocation.method(
          #getAllShows,
          [],
        ),
        returnValue: <_i17.TvShowCacheEntry>[],
      ) as List<_i17.TvShowCacheEntry>);

  @override
  _i8.Future<void> deleteShow(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #deleteShow,
          [tmdbId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addOrUpdateEpisode(_i17.TvEpisodeCacheEntry? episode) =>
      (super.noSuchMethod(
        Invocation.method(
          #addOrUpdateEpisode,
          [episode],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i17.TvEpisodeCacheEntry? getEpisode(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getEpisode,
        [
          showId,
          seasonNumber,
          episodeNumber,
        ],
      )) as _i17.TvEpisodeCacheEntry?);

  @override
  List<_i17.TvEpisodeCacheEntry> getEpisodesForShow(int? showId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEpisodesForShow,
          [showId],
        ),
        returnValue: <_i17.TvEpisodeCacheEntry>[],
      ) as List<_i17.TvEpisodeCacheEntry>);

  @override
  List<_i17.TvEpisodeCacheEntry> getAllEpisodes() => (super.noSuchMethod(
        Invocation.method(
          #getAllEpisodes,
          [],
        ),
        returnValue: <_i17.TvEpisodeCacheEntry>[],
      ) as List<_i17.TvEpisodeCacheEntry>);

  @override
  _i8.Future<void> deleteEpisode(
    int? showId,
    int? seasonNumber,
    int? episodeNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteEpisode,
          [
            showId,
            seasonNumber,
            episodeNumber,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> deleteAllEpisodesForShow(int? showId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllEpisodesForShow,
          [showId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [ContributorDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContributorDetailRepository extends _i1.Mock
    implements _i18.ContributorDetailRepository {
  MockContributorDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i19.ContributorDetail? getContributorDetail(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getContributorDetail,
        [tmdbId],
      )) as _i19.ContributorDetail?);

  @override
  _i8.Future<void> cacheContributorDetail(_i19.ContributorDetail? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheContributorDetail,
          [detail],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isCached(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #isCached,
          [tmdbId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> deleteContributorDetail(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #deleteContributorDetail,
          [tmdbId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearOldCache() => (super.noSuchMethod(
        Invocation.method(
          #clearOldCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  List<_i19.ContributorDetail> getAllCachedDetails() => (super.noSuchMethod(
        Invocation.method(
          #getAllCachedDetails,
          [],
        ),
        returnValue: <_i19.ContributorDetail>[],
      ) as List<_i19.ContributorDetail>);

  @override
  List<_i19.ContributorDetail> getCachedDetailsForContributors(
          List<int>? tmdbIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDetailsForContributors,
          [tmdbIds],
        ),
        returnValue: <_i19.ContributorDetail>[],
      ) as List<_i19.ContributorDetail>);

  @override
  _i8.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> migrateToStringKeys() => (super.noSuchMethod(
        Invocation.method(
          #migrateToStringKeys,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [MovieDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieDetailRepository extends _i1.Mock
    implements _i20.MovieDetailRepository {
  MockMovieDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i21.MovieDetail? getMovieDetail(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getMovieDetail,
        [tmdbId],
      )) as _i21.MovieDetail?);

  @override
  _i8.Future<void> cacheMovieDetail(_i21.MovieDetail? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheMovieDetail,
          [detail],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isCached(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #isCached,
          [tmdbId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> clearOldCache() => (super.noSuchMethod(
        Invocation.method(
          #clearOldCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  List<_i21.MovieDetail> getAllCachedDetails() => (super.noSuchMethod(
        Invocation.method(
          #getAllCachedDetails,
          [],
        ),
        returnValue: <_i21.MovieDetail>[],
      ) as List<_i21.MovieDetail>);

  @override
  List<_i21.MovieDetail> getCachedDetailsForMovies(List<int>? tmdbIds) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedDetailsForMovies,
          [tmdbIds],
        ),
        returnValue: <_i21.MovieDetail>[],
      ) as List<_i21.MovieDetail>);

  @override
  _i8.Future<void> deleteMovieDetail(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMovieDetail,
          [tmdbId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [TvDetailRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvDetailRepository extends _i1.Mock
    implements _i22.TvDetailRepository {
  MockTvDetailRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i23.TvShowDetail? getTvShowDetail(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getTvShowDetail,
        [tmdbId],
      )) as _i23.TvShowDetail?);

  @override
  _i8.Future<void> cacheTvShowDetail(_i23.TvShowDetail? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTvShowDetail,
          [detail],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isShowCached(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #isShowCached,
          [tmdbId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i23.TvSeasonDetail? getTvSeasonDetail(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getTvSeasonDetail,
        [
          showId,
          seasonNumber,
        ],
      )) as _i23.TvSeasonDetail?);

  @override
  _i23.TvSeasonDetail? getTvSeasonDetailExplicit(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getTvSeasonDetailExplicit,
        [
          showId,
          seasonNumber,
        ],
      )) as _i23.TvSeasonDetail?);

  @override
  _i8.Future<void> cacheTvSeasonDetail(_i23.TvSeasonDetail? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTvSeasonDetail,
          [detail],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isSeasonCached(
    int? showId,
    int? seasonNumber,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isSeasonCached,
          [
            showId,
            seasonNumber,
          ],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i23.TvEpisodeDetail? getTvEpisodeDetail(int? tmdbId) =>
      (super.noSuchMethod(Invocation.method(
        #getTvEpisodeDetail,
        [tmdbId],
      )) as _i23.TvEpisodeDetail?);

  @override
  _i8.Future<void> cacheTvEpisodeDetail(_i23.TvEpisodeDetail? detail) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTvEpisodeDetail,
          [detail],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  bool isEpisodeCached(int? tmdbId) => (super.noSuchMethod(
        Invocation.method(
          #isEpisodeCached,
          [tmdbId],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i8.Future<void> clearAllCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAllCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i24.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set onAction(dynamic Function(String)? _onAction) => super.noSuchMethod(
        Invocation.setter(
          #onAction,
          _onAction,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> init({dynamic Function(String)? onAction}) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
          {#onAction: onAction},
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> showNotification({
    required int? id,
    required String? title,
    required String? body,
    String? payload,
    String? imagePath,
    List<String>? imagePaths,
    List<String>? releaseDates,
    int? totalMovieCount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showNotification,
          [],
          {
            #id: id,
            #title: title,
            #body: body,
            #payload: payload,
            #imagePath: imagePath,
            #imagePaths: imagePaths,
            #releaseDates: releaseDates,
            #totalMovieCount: totalMovieCount,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i25.NotificationAppLaunchDetails?>
      getNotificationLaunchDetails() => (super.noSuchMethod(
            Invocation.method(
              #getNotificationLaunchDetails,
              [],
            ),
            returnValue: _i8.Future<_i25.NotificationAppLaunchDetails?>.value(),
          ) as _i8.Future<_i25.NotificationAppLaunchDetails?>);

  @override
  _i8.Future<void> showTestNotification() => (super.noSuchMethod(
        Invocation.method(
          #showTestNotification,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [WatchlistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchlistRepository extends _i1.Mock
    implements _i26.WatchlistRepository {
  MockWatchlistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<_i4.WatchlistEntry> addWork({
    required int? tmdbId,
    required _i19.WorkType? type,
    required String? title,
    String? posterPath,
    DateTime? releaseDate,
    _i19.ReleaseType? releaseType,
    List<_i4.ContributorSnapshot>? followedContributors,
    _i10.ReleaseNotificationPreferences? releaseNotificationPrefs,
    _i10.TvNotificationPreferences? tvNotificationPrefs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addWork,
          [],
          {
            #tmdbId: tmdbId,
            #type: type,
            #title: title,
            #posterPath: posterPath,
            #releaseDate: releaseDate,
            #releaseType: releaseType,
            #followedContributors: followedContributors,
            #releaseNotificationPrefs: releaseNotificationPrefs,
            #tvNotificationPrefs: tvNotificationPrefs,
          },
        ),
        returnValue: _i8.Future<_i4.WatchlistEntry>.value(_FakeWatchlistEntry_7(
          this,
          Invocation.method(
            #addWork,
            [],
            {
              #tmdbId: tmdbId,
              #type: type,
              #title: title,
              #posterPath: posterPath,
              #releaseDate: releaseDate,
              #releaseType: releaseType,
              #followedContributors: followedContributors,
              #releaseNotificationPrefs: releaseNotificationPrefs,
              #tvNotificationPrefs: tvNotificationPrefs,
            },
          ),
        )),
      ) as _i8.Future<_i4.WatchlistEntry>);

  @override
  _i8.Future<void> removeWork(
    int? tmdbId,
    _i19.WorkType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeWork,
          [
            tmdbId,
            type,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  List<_i4.WatchlistEntry> getWorks() => (super.noSuchMethod(
        Invocation.method(
          #getWorks,
          [],
        ),
        returnValue: <_i4.WatchlistEntry>[],
      ) as List<_i4.WatchlistEntry>);

  @override
  List<_i4.WatchlistEntry> getWorksByType(_i19.WorkType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWorksByType,
          [type],
        ),
        returnValue: <_i4.WatchlistEntry>[],
      ) as List<_i4.WatchlistEntry>);

  @override
  _i8.Future<bool> isWorkInWatchlist(
    int? tmdbId,
    _i19.WorkType? type,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #isWorkInWatchlist,
          [
            tmdbId,
            type,
          ],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i4.WatchlistEntry? getWork(
    int? tmdbId,
    _i19.WorkType? type,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getWork,
        [
          tmdbId,
          type,
        ],
      )) as _i4.WatchlistEntry?);

  @override
  _i8.Future<void> updateWork(_i4.WatchlistEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #updateWork,
          [entry],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setSnoozed(
    int? tmdbId,
    _i19.WorkType? type,
    bool? snoozed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setSnoozed,
          [
            tmdbId,
            type,
            snoozed,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> setNotificationsSnoozed(
    int? tmdbId,
    _i19.WorkType? type,
    bool? snoozed,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #setNotificationsSnoozed,
          [
            tmdbId,
            type,
            snoozed,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateUserRank(
    int? tmdbId,
    _i19.WorkType? type,
    int? rank,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserRank,
          [
            tmdbId,
            type,
            rank,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateContributorSnapshot(
    int? tmdbId,
    _i19.WorkType? type,
    List<_i4.ContributorSnapshot>? contributors,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateContributorSnapshot,
          [
            tmdbId,
            type,
            contributors,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateReleaseNotificationPreferences(
    int? tmdbId,
    _i19.WorkType? type,
    _i10.ReleaseNotificationPreferences? preferences,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateReleaseNotificationPreferences,
          [
            tmdbId,
            type,
            preferences,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> updateTvNotificationPreferences(
    int? tmdbId,
    _i10.TvNotificationPreferences? preferences,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateTvNotificationPreferences,
          [
            tmdbId,
            preferences,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> addStatusRecord(
    int? tmdbId,
    _i19.WorkType? type,
    _i27.StatusRecord? record,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addStatusRecord,
          [
            tmdbId,
            type,
            record,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeStatusRecord(
    int? tmdbId,
    _i19.WorkType? type,
    _i27.WatchStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeStatusRecord,
          [
            tmdbId,
            type,
            status,
          ],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [GoogleSignIn].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignIn extends _i1.Mock implements _i5.GoogleSignIn {
  MockGoogleSignIn() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i28.SignInOption get signInOption => (super.noSuchMethod(
        Invocation.getter(#signInOption),
        returnValue: _i28.SignInOption.standard,
      ) as _i28.SignInOption);

  @override
  List<String> get scopes => (super.noSuchMethod(
        Invocation.getter(#scopes),
        returnValue: <String>[],
      ) as List<String>);

  @override
  bool get forceCodeForRefreshToken => (super.noSuchMethod(
        Invocation.getter(#forceCodeForRefreshToken),
        returnValue: false,
      ) as bool);

  @override
  _i8.Stream<_i5.GoogleSignInAccount?> get onCurrentUserChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onCurrentUserChanged),
        returnValue: _i8.Stream<_i5.GoogleSignInAccount?>.empty(),
      ) as _i8.Stream<_i5.GoogleSignInAccount?>);

  @override
  _i8.Future<_i5.GoogleSignInAccount?> signInSilently({
    bool? suppressErrors = true,
    bool? reAuthenticate = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInSilently,
          [],
          {
            #suppressErrors: suppressErrors,
            #reAuthenticate: reAuthenticate,
          },
        ),
        returnValue: _i8.Future<_i5.GoogleSignInAccount?>.value(),
      ) as _i8.Future<_i5.GoogleSignInAccount?>);

  @override
  _i8.Future<bool> isSignedIn() => (super.noSuchMethod(
        Invocation.method(
          #isSignedIn,
          [],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<_i5.GoogleSignInAccount?> signIn() => (super.noSuchMethod(
        Invocation.method(
          #signIn,
          [],
        ),
        returnValue: _i8.Future<_i5.GoogleSignInAccount?>.value(),
      ) as _i8.Future<_i5.GoogleSignInAccount?>);

  @override
  _i8.Future<_i5.GoogleSignInAccount?> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i8.Future<_i5.GoogleSignInAccount?>.value(),
      ) as _i8.Future<_i5.GoogleSignInAccount?>);

  @override
  _i8.Future<_i5.GoogleSignInAccount?> disconnect() => (super.noSuchMethod(
        Invocation.method(
          #disconnect,
          [],
        ),
        returnValue: _i8.Future<_i5.GoogleSignInAccount?>.value(),
      ) as _i8.Future<_i5.GoogleSignInAccount?>);

  @override
  _i8.Future<bool> requestScopes(List<String>? scopes) => (super.noSuchMethod(
        Invocation.method(
          #requestScopes,
          [scopes],
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<bool> canAccessScopes(
    List<String>? scopes, {
    String? accessToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #canAccessScopes,
          [scopes],
          {#accessToken: accessToken},
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);
}

/// A class which mocks [GoogleSignInAuthentication].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleSignInAuthentication extends _i1.Mock
    implements _i5.GoogleSignInAuthentication {
  MockGoogleSignInAuthentication() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [GoogleSignInAccount].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockGoogleSignInAccount extends _i1.Mock
    implements _i5.GoogleSignInAccount {
  MockGoogleSignInAccount() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get email => (super.noSuchMethod(
        Invocation.getter(#email),
        returnValue: _i29.dummyValue<String>(
          this,
          Invocation.getter(#email),
        ),
      ) as String);

  @override
  String get id => (super.noSuchMethod(
        Invocation.getter(#id),
        returnValue: _i29.dummyValue<String>(
          this,
          Invocation.getter(#id),
        ),
      ) as String);

  @override
  _i8.Future<_i5.GoogleSignInAuthentication> get authentication =>
      (super.noSuchMethod(
        Invocation.getter(#authentication),
        returnValue: _i8.Future<_i5.GoogleSignInAuthentication>.value(
            _FakeGoogleSignInAuthentication_8(
          this,
          Invocation.getter(#authentication),
        )),
      ) as _i8.Future<_i5.GoogleSignInAuthentication>);

  @override
  _i8.Future<Map<String, String>> get authHeaders => (super.noSuchMethod(
        Invocation.getter(#authHeaders),
        returnValue: _i8.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<void> clearAuthCache() => (super.noSuchMethod(
        Invocation.method(
          #clearAuthCache,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i6.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.IOSOptions get iOptions => (super.noSuchMethod(
        Invocation.getter(#iOptions),
        returnValue: _FakeIOSOptions_9(
          this,
          Invocation.getter(#iOptions),
        ),
      ) as _i6.IOSOptions);

  @override
  _i6.AndroidOptions get aOptions => (super.noSuchMethod(
        Invocation.getter(#aOptions),
        returnValue: _FakeAndroidOptions_10(
          this,
          Invocation.getter(#aOptions),
        ),
      ) as _i6.AndroidOptions);

  @override
  _i6.LinuxOptions get lOptions => (super.noSuchMethod(
        Invocation.getter(#lOptions),
        returnValue: _FakeLinuxOptions_11(
          this,
          Invocation.getter(#lOptions),
        ),
      ) as _i6.LinuxOptions);

  @override
  _i6.WindowsOptions get wOptions => (super.noSuchMethod(
        Invocation.getter(#wOptions),
        returnValue: _FakeWindowsOptions_12(
          this,
          Invocation.getter(#wOptions),
        ),
      ) as _i6.WindowsOptions);

  @override
  _i6.WebOptions get webOptions => (super.noSuchMethod(
        Invocation.getter(#webOptions),
        returnValue: _FakeWebOptions_13(
          this,
          Invocation.getter(#webOptions),
        ),
      ) as _i6.WebOptions);

  @override
  _i6.AppleOptions get mOptions => (super.noSuchMethod(
        Invocation.getter(#mOptions),
        returnValue: _FakeAppleOptions_14(
          this,
          Invocation.getter(#mOptions),
        ),
      ) as _i6.AppleOptions);

  @override
  Map<String, List<_i30.ValueChanged<String?>>> get getListeners =>
      (super.noSuchMethod(
        Invocation.getter(#getListeners),
        returnValue: <String, List<_i30.ValueChanged<String?>>>{},
      ) as Map<String, List<_i30.ValueChanged<String?>>>);

  @override
  void registerListener({
    required String? key,
    required _i30.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #registerListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterListener({
    required String? key,
    required _i30.ValueChanged<String?>? listener,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterListener,
          [],
          {
            #key: key,
            #listener: listener,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(
          #unregisterAllListenersForKey,
          [],
          {#key: key},
        ),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
        Invocation.method(
          #unregisterAllListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<void> write({
    required String? key,
    required String? value,
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [],
          {
            #key: key,
            #value: value,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String?> read({
    required String? key,
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #read,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<bool> containsKey({
    required String? key,
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i8.Future<bool>.value(false),
      ) as _i8.Future<bool>);

  @override
  _i8.Future<void> delete({
    required String? key,
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #key: key,
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<Map<String, String>> readAll({
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #readAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i8.Future<Map<String, String>>.value(<String, String>{}),
      ) as _i8.Future<Map<String, String>>);

  @override
  _i8.Future<void> deleteAll({
    _i6.AppleOptions? iOptions,
    _i6.AndroidOptions? aOptions,
    _i6.LinuxOptions? lOptions,
    _i6.WebOptions? webOptions,
    _i6.AppleOptions? mOptions,
    _i6.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [],
          {
            #iOptions: iOptions,
            #aOptions: aOptions,
            #lOptions: lOptions,
            #webOptions: webOptions,
            #mOptions: mOptions,
            #wOptions: wOptions,
          },
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<bool?> isCupertinoProtectedDataAvailable() => (super.noSuchMethod(
        Invocation.method(
          #isCupertinoProtectedDataAvailable,
          [],
        ),
        returnValue: _i8.Future<bool?>.value(),
      ) as _i8.Future<bool?>);
}
